name: CI
on:
  push:
    branches:
      - "main"
  pull_request: {}
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'daren-malfait/dz-opstellingen' && github.event_name == 'push' }}
    steps:
      - name: Cancel ongoing builds
        uses: styfle/cancel-workflow-action@0.9.0

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: 🚀
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
